use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Message {
    Hello { device_name: String },
    SendNote {
        from_peer: String,
        /// Argon2id salt used to derive the transfer key (generated by sender).
        transfer_salt: Vec<u8>,
        /// ChaCha20-Poly1305 nonce for transfer_ct.
        transfer_nonce: Vec<u8>,
        /// Encrypted TransferBlob bytes.
        transfer_ct: Vec<u8>,
    },
    Ack { transfer_id: String },
    Reject { reason: String },
}

#[cfg(test)]
mod tests {
    use super::*;

    fn roundtrip(msg: &Message) -> Message {
        let bytes = serde_json::to_vec(msg).unwrap();
        serde_json::from_slice(&bytes).unwrap()
    }

    #[test]
    fn hello_roundtrip() {
        let msg = Message::Hello { device_name: "Alice".into() };
        let decoded = roundtrip(&msg);
        assert!(matches!(decoded, Message::Hello { device_name } if device_name == "Alice"));
    }

    #[test]
    fn send_note_roundtrip() {
        let msg = Message::SendNote {
            from_peer: "bob.local".into(),
            transfer_salt: vec![1, 2, 3],
            transfer_nonce: vec![4, 5, 6],
            transfer_ct: vec![7, 8, 9],
        };
        let decoded = roundtrip(&msg);
        assert!(matches!(decoded, Message::SendNote { from_peer, .. } if from_peer == "bob.local"));
    }

    #[test]
    fn ack_roundtrip() {
        let msg = Message::Ack { transfer_id: "tid-123".into() };
        let decoded = roundtrip(&msg);
        assert!(matches!(decoded, Message::Ack { transfer_id } if transfer_id == "tid-123"));
    }

    #[test]
    fn reject_roundtrip() {
        let msg = Message::Reject { reason: "bad passphrase".into() };
        let decoded = roundtrip(&msg);
        assert!(matches!(decoded, Message::Reject { reason } if reason == "bad passphrase"));
    }

    #[test]
    fn unknown_type_deserialize_fails() {
        let bad = r#"{"type":"unknown_type","foo":"bar"}"#;
        assert!(serde_json::from_str::<Message>(bad).is_err());
    }
}
