<#
Vendors the app's two webfonts into static/fonts/ so the shipped app never
touches the network. Run once; re-run only when the icon list below changes.

    powershell -ExecutionPolicy Bypass -File scripts/fetch-fonts.ps1

Material Symbols is subsetted to the glyphs the UI actually renders (a few KB
instead of several MB). If you add a new icon to the UI, add it to $Icons and
re-run this, or it will render as its literal name.
#>

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
$OutDir = Join-Path $Root "static\fonts"
$UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

$Icons = @(
  "add", "arrow_back", "arrow_downward", "arrow_forward", "arrow_upward",
  "assignment", "check", "check_box", "checklist", "checklist_rtl",
  "chevron_right", "close", "code", "content_copy", "create_new_folder",
  "dark_mode", "data_object", "delete",
  "description", "download", "edit", "edit_note", "emoji_emotions",
  "expand_more", "file_download", "file_upload", "folder",
  "format_bold", "format_color_reset",
  "format_color_text", "format_italic", "format_list_bulleted",
  "format_list_numbered", "format_quote", "format_strikethrough",
  "history", "horizontal_rule", "image", "inbox", "info", "key",
  "keyboard_arrow_down",
  "keyboard_arrow_up", "lan", "light_mode", "link", "lock", "lock_open",
  "menu", "military_tech", "more_horiz", "more_vert", "note_add",
  "open_in_new", "palette",
  "password", "push_pin", "qr_code_2", "qr_code_scanner",
  "radio_button_checked", "radio_button_unchecked", "refresh", "search",
  "search_off", "send", "settings", "smartphone", "sticky_note_2",
  "swap_horiz", "swap_vert", "table_chart", "table_rows", "title", "trophy",
  "upload", "view_column", "view_kanban", "visibility", "visibility_off",
  "warning", "wifi_tethering"
) -join ","

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

function Get-FontCss($url, $prefix) {
  $css = (Invoke-WebRequest -Uri $url -UserAgent $UA -UseBasicParsing).Content
  # These are variable fonts: every weight shares one file per unicode-range, so
  # the same URL appears many times. Dedupe or we download and commit copies.
  $seen = @{}
  $i = 0
  foreach ($m in [regex]::Matches($css, 'url\((https://[^\)]+)\)')) {
    $remote = $m.Groups[1].Value
    if ($seen.ContainsKey($remote)) { continue }
    $name = "$prefix-$i.woff2"
    $seen[$remote] = $name
    Invoke-WebRequest -Uri $remote -UserAgent $UA -OutFile (Join-Path $OutDir $name) -UseBasicParsing
    $css = $css.Replace($remote, "./$name")
    Write-Host "  $name"
    $i++
  }
  return $css
}

Write-Host "DM Sans:"
$sans = Get-FontCss "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700;900&display=swap" "dm-sans"

Write-Host "Material Symbols (subset, $(($Icons -split ',').Count) icons):"
$symbols = Get-FontCss "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&icon_names=$Icons&display=block" "material-symbols"

$header = "/* Generated by scripts/fetch-fonts.ps1 - do not edit by hand. */`n"
Set-Content -Path (Join-Path $OutDir "fonts.css") -Value ($header + $sans + "`n" + $symbols) -Encoding utf8

Write-Host "`nWrote $OutDir\fonts.css"
