use crate::crypto::tls::TofuVerifier;
use sqlx::SqlitePool;
use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
};

#[derive(Debug, Clone)]
pub struct Peer {
    pub id: String,
    pub name: String,
    pub address: String,
    pub port: u16,
    pub via: TransportKind,
}

#[derive(Debug, Clone, PartialEq)]
#[allow(dead_code)]
pub enum TransportKind {
    Lan,
    Ble,
}

/// A note received from a peer, stored encrypted until the user provides the passphrase.
#[derive(Debug, Clone)]
pub struct PendingTransfer {
    pub transfer_id: String,
    pub from_peer: String,
    /// Argon2id salt used to derive the transfer key (generated by sender).
    pub transfer_salt: Vec<u8>,
    /// ChaCha20-Poly1305 nonce for the transfer ciphertext.
    pub transfer_nonce: Vec<u8>,
    /// Encrypted TransferBlob bytes — decrypted only when passphrase is entered.
    pub transfer_ct: Vec<u8>,
    pub received_at: i64,
}

#[derive(Clone)]
pub struct AppState {
    pub db: SqlitePool,
    /// Device key derived at startup from machine UID + app UUID. Never changes.
    pub device_key: [u8; 32],
    pub peers: Arc<Mutex<Vec<Peer>>>,
    pub pending_transfers: Arc<Mutex<HashMap<String, PendingTransfer>>>,
    pub tofu: Arc<TofuVerifier>,
}

impl AppState {
    pub fn new(db: SqlitePool, device_key: [u8; 32]) -> Self {
        let provider = Arc::new(rustls::crypto::ring::default_provider());
        Self {
            db,
            device_key,
            peers: Arc::new(Mutex::new(Vec::new())),
            pending_transfers: Arc::new(Mutex::new(HashMap::new())),
            tofu: Arc::new(TofuVerifier::new(provider)),
        }
    }

    pub fn add_pending(&self, transfer: PendingTransfer) {
        self.pending_transfers
            .lock()
            .unwrap()
            .insert(transfer.transfer_id.clone(), transfer);
    }

    pub fn take_pending(&self, transfer_id: &str) -> Option<PendingTransfer> {
        self.pending_transfers.lock().unwrap().remove(transfer_id)
    }

    pub fn list_pending(&self) -> Vec<PendingTransfer> {
        self.pending_transfers.lock().unwrap().values().cloned().collect()
    }
}
