ALTER TABLE notes ADD COLUMN pinned INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN bg_color TEXT;
ALTER TABLE notes ADD COLUMN bg_image TEXT;
ALTER TABLE notes ADD COLUMN show_preview INTEGER NOT NULL DEFAULT 1;
ALTER TABLE notes ADD COLUMN preview_text TEXT;
